# Wearable Options
armor: 2

# Damageable Options
max_durability: 77
repair_ingredient: minecraft:copper

# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:protection
  - minecraft:fire_protection
  - minecraft:blast_protection
  - minecraft:projectile_protection
  - minecraft:respiration
  - minecraft:aqua_affinity
  - minecraft:unbreaking
  - minecraft:mending