# Wearable Options
armor: 5

# Damageable Options
max_durability: 112
repair_ingredient: minecraft:copper

# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:protection
  - minecraft:fire_protection
  - minecraft:blast_protection
  - minecraft:projectile_protection
  - minecraft:thorns
  - minecraft:unbreaking
  - minecraft:mending