# Tool Options
tool_tier: minecraft:diamond
tool_category: minecraft:hoe
break_speed: 8
attack_damage: 1
attack_speed: 4.0
can_sweep_attack: false
can_break_blocks_in_creative: true

# Damageable Options
max_durability: 1561
item_damage_on_attack_entity: 2
item_damage_on_break_block: 1
repair_ingredient: minecraft:emerald

# Enchantable Options
enchantment_value: 10
supported_enchantments:
  - minecraft:efficiency
  - minecraft:silk_touch
  - minecraft:fortune
  - minecraft:unbreaking
  - minecraft:mending